---

- include: debian.yml
- include: vmhosts.yml

- name: Gather facts
  hosts: router
  tasks:
    - name: Execute setup
      action: setup

- include: website.yml
- include: common.yml
- include: observium.yml
- include: edge.yml

- include: core.yml
- include: site-edgeos.yml
