---

- name: Gather facts
  hosts: router
  tasks:
    - name: Execute setup
      action: setup

- name: Configure SSH users for website deployment
  hosts:
  - website
  roles:
  - { role: ssh, tags: ssh}

- name: Set up common configuration
  hosts:
  - backbone
  - observium
  roles:
  - { role: common, tags: common }
  - { role: sshd, tags: sshd }

- name: Configure monitoring
  hosts: observium
  roles:
  - { role: observium, tags: observium }

- name: Configure edge routers
  hosts: edge
  roles:
  - { role: edge, tags: edge }

- name: Configure core router
  hosts: core
  roles:
  - { role: core, tags: core }
  - { role: dns-resolver, tags: dns-resolver }

- name: Configure site routers (edgeos)
  hosts: site-edgeos
  roles:
  - { role: router, tags: ["site-edgeos","site"] }
  - { role: site, tags: ["site-edgeos","site"] }

- include: vmhosts.yml