---

- name: Set up common configuration
  hosts: all
  roles:
  - { role: common, tags: common }

- name: Configure monitoring
  hosts: observium
  roles:
  - { role: observium, tags: observium }

- name: Configure edge routers
  hosts: edge
  roles:
  - { role: edge, tags: edge }

- name: Configure core router
  hosts: core
  roles:
  - { role: core, tags: core }
