---

- name: Gather facts
  hosts: all
  tasks:
    - name: Execute setup
      action: setup

- name: Set up common configuration
  hosts:
  - router
  - observium
  roles:
  - { role: common, tags: common }
  - { role: sshd, tags: sshd }

- name: Configure monitoring
  hosts: observium
  roles:
  - { role: observium, tags: observium }

- name: Configure edge routers
  hosts: edge
  roles:
  - { role: edge, tags: edge }

- name: Configure core router
  hosts: core
  roles:
  - { role: core, tags: core }
  - { role: dns-resolver, tags: dns-resolver }
