---

- include: loopback.yml
- include: gretun.yml

- name: Add package repository
  apt_repository: repo='deb http://bird.network.cz/debian/ jessie main'
  register: repo

- name: Add package key
  apt_key: url=http://bird.network.cz/debian/apt.key
  when: repo | changed

- name: Update package cache
  apt: update_cache=yes
  when: repo | changed

- name: Install package
  apt: name=bird state=present

- include: bird.yml
  tags: ipv4

- include: bird6.yml
  tags: ipv6

- name: Enable IPv4 forward
  sysctl: name="net.ipv4.ip_forward" value=1 sysctl_set=yes state=present reload=yes

- name: Enable IPv6 forward
  sysctl: name="net.ipv6.conf.all.forwarding" value=1 sysctl_set=yes state=present reload=yes
