---

loopback_address: "{{ internal_ipv4 | ipsubnet(loopback_subnets.backbone.ipv4_size, loopback_subnets.backbone.seq) | ipsubnet(loopback_subnets.edge.ipv4_size, loopback_subnets.edge.seq) | ipaddr(seq) | ipaddr('address') }}"
