---

- name: Install requirements
  apt: name={{ item }} state=present
  with_items:
  - liblog4cplus-1.1-9

- name: Install packages
  apt: name=kea state=present

- name: Create data directory
  file: path=/var/kea state=directory

- name: Create run state directory
  file: path=/run/kea state=directory

- name: Configure unit
  template: src=kea-dhcp4.service.j2 dest=/etc/systemd/system/kea-dhcp4.service
  notify: reload systemd

- name: Configure service
  template: src=kea.conf.j2 dest=/etc/kea/kea.conf
  notify: reload kea-dhcp4

- name: Enable service
  service: name=kea-dhcp4 enabled=yes
