---

- name: Install libvirt packages
  package: name={{ item }} state=present
  with_items:
  - libvirt-daemon
  - libvirt-daemon-system
  - python-libvirt
  - python-lxml
  - virtinst

- name: Enable service
  service: name=libvirtd enabled=yes
  notify: start libvirtd

- include: network.yml

- include: debianinstall.yml